apiVersion: v1
kind: ServiceAccount
metadata:
  name: rospo
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rospo-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs: 
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rospo
subjects:
- kind: ServiceAccount
  name: rospo
  namespace: default
roleRef:
  kind: ClusterRole
  name: rospo-role
  apiGroup: rbac.authorization.k8s.io