services:
  rospo:
    restart: unless-stopped
    image: ghcr.io/ferama/rospo:main
    container_name: rospo
    command:
      - run
      - /rospo.yaml
    network_mode: "host"
    logging:
      driver: json-file
      options:
        max-size: "8m"
    volumes:
      - ./rospo.yaml:/rospo.yaml
      - ./server_key:/server_key
      - ./authorized_keys:/authorized_keys
      - ./server_key.pub:/server_key.pub