# the ssh client configuration
sshclient:
  # OPTIONAL: private key path. Default to ~/.ssh/id_rsa
  identity: "~/.ssh/id_rsa"
  # REQUIRED: server url
  server: user@192.168.0.10:22
  # OPTIONAL: if the check against know_hosts is enabled or not
  # default true
  insecure: false
  # OPTIONAL: list of jump hosts hop to traverse
  # comment the section for a direct connection
  jump_hosts:
    - uri: user@server:port
      # OPTIONAL: private key path. Default to ~/.ssh/id_rsa
      identity: "~/.ssh/id_rsa"

# List of tunnels configuration. Requires that the sshclient section
# is configured too. We are going to use one ssh connection 
# configured into the sshclient section to enable multiple tunnels
tunnel:
  - remote: ":8000"
    local: ":8000"
    forward: yes
  - remote: ":2222"
    local: ":2222"
    forward: no

# sshd server configuration
# Comment this section to disable the embedded ssh server
sshd:
  server_key: "./server_key"
  authorized_keys: "./authorized_keys"
  port: "2222"