mod client;
mod paths;
mod types;

pub use types::{
    Client, ProgressReporter, TransferOptions, DEFAULT_CHUNK_SIZE, DEFAULT_CONCURRENT_DOWNLOADS,
    DEFAULT_CONCURRENT_UPLOADS, DEFAULT_DOWNLOAD_MAX_WORKERS, DEFAULT_MAX_WORKERS,
    DEFAULT_UPLOAD_MAX_WORKERS,
};
