name: docker

on:
  push:
    # branches:
    #   - 'main'
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]
          then 
              TAG="latest"
          else
              TAG=${GITHUB_REF/refs\/tags\/v/}
          fi
          echo ::set-output name=VERSION::$TAG

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./hack/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rospo:${{ steps.get_version.outputs.VERSION }}