name: docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tags
        id: get_tags
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]
          then 
              TAG=${{ secrets.DOCKERHUB_USERNAME }}/rospo:dev
              echo ::set-output name=VERSION::dev-docker
              echo ::set-output name=TAG1::$TAG
              echo ::set-output name=TAG2::$TAG
          else
              TAG=${GITHUB_REF/refs\/tags\/v/}
              echo ::set-output name=VERSION::$TAG
              echo ::set-output name=TAG1::${{ secrets.DOCKERHUB_USERNAME }}/rospo:latest
              echo ::set-output name=TAG2::${{ secrets.DOCKERHUB_USERNAME }}/rospo:$TAG
          fi

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./hack/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          build_args: VERSION=${{ steps.get_tags.outputs.VERSION }}
          tags: |
            ${{ steps.get_tags.outputs.TAG1 }}
            ${{ steps.get_tags.outputs.TAG2 }}
      
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ferama/rospo